name: Run Slack Approval Test

on:
  workflow_dispatch:
    inputs:
      channel_id:
        required: true
        type: string
        default: "C08R4TBBX7U"

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Send base message to Slack
        id: send-message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ github.event.inputs.channel_id }}"
            text: "Slack approval workflow initiated."

      - name: send approval
        uses: TigerWest/slack-approval@v1.0.1
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ github.event.inputs.channel_id }}
        timeout-minutes: 10
        with:
            approvers: U08QR864Z3L
            minimumApprovalCount: 1
            baseMessageTs: "${{ steps.send-message.outputs.ts }}"
            baseMessagePayload: |
              {}
            successMessagePayload: |
              {}
            failMessagePayload: |
              {}
    
      - name: work
        run: |
          echo "Approval received, continuing with the workflow"
